server:
  port: 8093
  
spring:
  application:
    name: CONSUMER-ONE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
